[package]
name = "com/jcc/minimal"
aid = "A000000062030101"
version = "1.0"

[applet]
aid = "A00000006203010101"
class = "MinimalApplet"

[options]
javacard_version = "3.0.4"

[build]
command = "clang -S -emit-llvm -g -target wasm32-unknown-unknown -O1 -fno-jump-tables -nostdinc -I $JCC_INCLUDE -I $JCC_INCLUDE/$JAVACARD_VERSION main.c -o build/main.ll"