[package]
name = "com/crystalpeak/musicvideo"
aid = "A0000000620300DEAD01"
version = "1.0"

[applet]
aid = "A0000000620300DEAD0101"
class = "Applet"

[options]
javacard_version = "3.0.4"
extended_apdu = true

[build]
command = "clang -S -emit-llvm -g -target wasm32-unknown-unknown -O1 -fno-jump-tables -nostdinc -I $JCC_INCLUDE -I $JCC_INCLUDE/$JAVACARD_VERSION main.c -o build/main.ll"

[driver]
game_name = "Music Video"
screen_width = 32
screen_height = 20
pixel_format = "2bpp"
target_fps = 4
input_mode = "none"
continuous_frames = true
