[package]
name = "com/crystalpeak/game2048"
aid = "A0000000620300F003"
version = "1.0"

[applet]
aid = "A0000000620300F00301"
class = "Applet"

[options]
javacard_version = "3.0.4"
extended_apdu = true

[build]
command = "clang -S -emit-llvm -g -target wasm32-unknown-unknown -O1 -fno-jump-tables -nostdinc -I $JCC_INCLUDE -I $JCC_INCLUDE/$JAVACARD_VERSION -I . main.c -o build/main.ll"

[driver]
game_name = "2048"
screen_width = 64
screen_height = 64
pixel_format = "4bpp"
target_fps = 30
input_mode = "direction"
continuous_frames = false
single_input = true
controls_wasd = true
palette = [
    [187, 173, 160],
    [205, 193, 180],
    [238, 228, 218],
    [237, 224, 200],
    [242, 177, 121],
    [245, 149, 99],
    [246, 124, 95],
    [246, 94, 59],
    [237, 207, 114],
    [237, 204, 97],
    [237, 200, 80],
    [237, 197, 63],
    [237, 194, 46],
    [119, 110, 101],
    [249, 246, 242],
    [187, 173, 160],
]