[package]
name = "com/crystalpeak/synth"
aid = "A0000000620300D00201"
version = "1.0"

[applet]
aid = "A0000000620300D0020101"
class = "Synth"

[options]
javacard_version = "3.0.4"
extended_apdu = true

[build]
command = "clang -S -emit-llvm -g -target wasm32-unknown-unknown -O1 -fno-jump-tables -nostdinc -I $JCC_ROOT/include main.c -o build/main.ll"

[driver]
game_name = "Synth"
input_mode = "keyboard"
continuous_frames = true
