[package]
name = "com/crystalpeak/pkmn"
aid = "A0000000620300F003"

[applet]
aid = "A0000000620300F00301"
class = "Applet"

[options]
javacard_version = "3.0.4"
extended_apdu = true

[build]
command = "clang -S -emit-llvm -g -target wasm32-unknown-unknown -O1 -fno-jump-tables -nostdinc -I $JCC_ROOT/include main.c -o build/main.ll"

[driver]
game_name = "PKMN"
screen_width = 48
screen_height = 32
pixel_format = "4bpp"
target_fps = 15
input_mode = "direction_button"
continuous_frames = true
single_input = true
controls_wasd = true
controls_space = "Select"
palette = [
    [0, 0, 0],
    [255, 255, 255],
    [210, 180, 140],
    [144, 238, 144],
    [60, 179, 60],
    [34, 177, 76],
    [0, 128, 0],
    [248, 216, 168],
    [248, 208, 48],
    [168, 112, 64],
    [232, 96, 72],
    [0, 200, 0],
    [200, 50, 50],
    [248, 248, 248],
    [88, 88, 88],
    [80, 60, 40],
]
