[package]
name = "com/crystalpeak/apple"
aid = "A0000000620300BA01"

[applet]
aid = "A0000000620300BA0101"
class = "Applet"

[options]
javacard_version = "3.0.4"

[build]
command = "clang -S -emit-llvm -g -target wasm32-unknown-unknown -O1 -fno-jump-tables -nostdinc -I $JCC_ROOT/include main.c -o build/main.ll"

[driver]
game_name = "Bad Apple"
screen_width = 32
screen_height = 20
pixel_format = "1bpp"
target_fps = 8
input_mode = "none"
continuous_frames = true
palette = [
    [8, 8, 8],
    [255, 255, 255],
]
